import { useListReports, getListReportsQueryKey } from "@workspace/api-client-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatNigerianDate } from "@/lib/utils";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { Download, FileText } from "lucide-react";

export default function ReportsPage() {
  const { data: reports, isLoading, isError } = useListReports({
    query: {
      queryKey: getListReportsQueryKey()
    }
  });

  if (isLoading) {
    return <ReportsSkeleton />;
  }

  if (isError || !reports) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
        <div className="text-center">
          <h2 className="text-lg font-semibold text-destructive">Failed to load reports</h2>
          <p className="text-sm text-muted-foreground">Please try refreshing the page.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">Generated Reports</h1>
        <p className="text-muted-foreground">Access all generated PDF temperament reports.</p>
      </div>

      <Card className="border-border bg-card">
        <CardHeader>
          <CardTitle>Report Archive</CardTitle>
          <CardDescription>List of all downloadable reports generated by the platform.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-12"></TableHead>
                <TableHead>Type</TableHead>
                <TableHead>User ID</TableHead>
                <TableHead>Session ID</TableHead>
                <TableHead>Generated On</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="h-24 text-center">
                    No reports generated yet.
                  </TableCell>
                </TableRow>
              ) : (
                reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell>
                      <FileText className="h-4 w-4 text-muted-foreground" />
                    </TableCell>
                    <TableCell className="capitalize font-medium">{report.reportType?.replace(/_/g, ' ') || 'Standard'}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">{report.userId ? report.userId.substring(0, 8) : '—'}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">{report.sessionId ? report.sessionId.substring(0, 8) : '—'}</TableCell>
                    <TableCell>{formatNigerianDate(report.createdAt)}</TableCell>
                    <TableCell className="text-right">
                      {report.reportUrl ? (
                        <Button variant="outline" size="sm" asChild>
                          <a href={report.reportUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
                            <Download className="h-3 w-3" />
                            Download
                          </a>
                        </Button>
                      ) : (
                        <span className="text-xs text-muted-foreground">Pending</span>
                      )}
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}

function ReportsSkeleton() {
  return (
    <div className="space-y-6">
      <div>
        <Skeleton className="h-9 w-48 mb-2" />
        <Skeleton className="h-5 w-72" />
      </div>
      <Card className="border-border bg-card">
        <CardHeader>
          <Skeleton className="h-6 w-32 mb-2" />
          <Skeleton className="h-4 w-64" />
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {[1, 2, 3, 4, 5].map((i) => (
              <Skeleton key={i} className="h-12 w-full" />
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
