import { Router, type IRouter } from "express";
import healthRouter from "./health";
import divisionsRouter from "./divisions";
import homepageRouter from "./homepage";
import messagesRouter from "./messages";
import adminRouter from "./admin";
import storageRouter from "./storage";
import galleryRouter from "./gallery";
import productsRouter from "./products";
import testimonialsRouter from "./testimonials";
import newsletterRouter from "./newsletter";
import heroSlidesRouter from "./hero-slides";
import servicesRouter from "./services";
import postsRouter from "./posts";
import tmTestsRouter from "./tm-tests";
import tmProfilesRouter from "./tm-profiles";
import tmPaymentsRouter from "./tm-payments";
import tmReportsRouter from "./tm-reports";
import tmAdminRouter from "./tm-admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(divisionsRouter);
router.use(homepageRouter);
router.use(messagesRouter);
router.use(adminRouter);
router.use(storageRouter);
router.use(galleryRouter);
router.use(productsRouter);
router.use(testimonialsRouter);
router.use(newsletterRouter);
router.use(heroSlidesRouter);
router.use(servicesRouter);
router.use(postsRouter);
router.use(tmTestsRouter);
router.use(tmProfilesRouter);
router.use(tmPaymentsRouter);
router.use(tmReportsRouter);
router.use(tmAdminRouter);

export default router;
